package com.huawei.digitalpayment.consumer.sfcui.buybundles.familyconnect;

public interface FamilyConnectDeleteBeneficiaryFragment_GeneratedInjector {
    void injectFamilyConnectDeleteBeneficiaryFragment(FamilyConnectDeleteBeneficiaryFragment familyConnectDeleteBeneficiaryFragment);
}
