package com.huawei.digitalpayment.consumer.sfcui.buybundles.familyconnect;

public interface FamilyConnectUpdateBeneficiaryFragment_GeneratedInjector {
    void injectFamilyConnectUpdateBeneficiaryFragment(FamilyConnectUpdateBeneficiaryFragment familyConnectUpdateBeneficiaryFragment);
}
