package com.huawei.digitalpayment.consumer.fixeddata.ui;

public interface FixedDataFamilyShareOnboardingActivity_GeneratedInjector {
    void injectFixedDataFamilyShareOnboardingActivity(FixedDataFamilyShareOnboardingActivity fixedDataFamilyShareOnboardingActivity);
}
