package com.huawei.digitalpayment.consumer.fixeddata.ui;

public interface FixedDataManageAccountChangeWifiPasswordActivity_GeneratedInjector {
    void injectFixedDataManageAccountChangeWifiPasswordActivity(FixedDataManageAccountChangeWifiPasswordActivity fixedDataManageAccountChangeWifiPasswordActivity);
}
