package com.huawei.digitalpayment.consumer.fixeddata.ui;

public interface FixedDataManageAccountConfirmationActivity_GeneratedInjector {
    void injectFixedDataManageAccountConfirmationActivity(FixedDataManageAccountConfirmationActivity fixedDataManageAccountConfirmationActivity);
}
