package com.huawei.digitalpayment.consumer.fixeddata.ui;

public interface FixedDataManageAccountChangeWifiNameActivity_GeneratedInjector {
    void injectFixedDataManageAccountChangeWifiNameActivity(FixedDataManageAccountChangeWifiNameActivity fixedDataManageAccountChangeWifiNameActivity);
}
